"""
Agent 4: Churn Prevention
Schedule: Daily at 10am IST
Input: Customers with >3 orders in last 60 days AND no order in last 14 days (churned high-value)
Output: DRAFT campaign targeting these customers with personalised message + discount offer
"""
import httpx
import logging
from datetime import datetime, timedelta
from typing import Dict, Any, List

logger = logging.getLogger(__name__)

CHURN_WINDOW_DAYS = 14
QUALIFYING_ORDER_COUNT = 3
QUALIFYING_PERIOD_DAYS = 60
RECOVERY_DISCOUNT_PERCENT = 15




CHURN_INSTRUCTION = """You are MaSoVa Churn Prevention Agent (ops).
1. list_stores then read_churn_segment per store (tool data only).
2. Optionally get_top_items for personalised copy.
3. create_draft_campaign (DRAFT) + notify_managers with rationale.
Never send live campaigns.
"""


def _churn_llm_runner():
    from ..runtime.ops_llm import make_ops_llm_runner
    from ..runtime.wrap import AGENT_ALLOWLISTS

    return make_ops_llm_runner(
        instruction=CHURN_INSTRUCTION,
        tool_names=list(AGENT_ALLOWLISTS["churn_prevention"]),
    )


async def run_churn_prevention():
    """Public entry — LLM tool loop + rule fallback."""
    from ..runtime.wrap import run_ops_agent
    from ..runtime.ops_llm import ops_prefer_llm

    prefer = ops_prefer_llm()
    return await run_ops_agent(
        "churn_prevention",
        "scheduled",
        _rule_run_churn_prevention,
        goal="Draft win-back campaigns for churned high-value customers",
        llm_runner=_churn_llm_runner() if prefer else None,
        prefer_llm=prefer,
    )

async def _rule_run_churn_prevention() -> Dict[str, Any]:
    from ..tools.ops_http import agent_token

    if not agent_token():
        logger.warning("AGENT_TOKEN not set — churn prevention skipped")
        return {"error": "AGENT_TOKEN not configured"}

    campaigns_created = 0
    customers_targeted = 0

    async with httpx.AsyncClient(timeout=30.0) as client:
        stores = await _get_stores(client)

        for store in stores:
            store_id = store["id"]
            churned_customers = await _find_churned_customers(client, store_id)

            if not churned_customers:
                continue

            customers_targeted += len(churned_customers)

            top_items = await _get_top_items(client, store_id)
            top_item_names = [item.get("name", "our bestsellers") for item in top_items[:3]]

            campaign_payload = {
                "storeId": store_id,
                "name": f"Win-Back Campaign — {datetime.now().strftime('%Y-%m-%d')}",
                "type": "WIN_BACK",
                "status": "DRAFT",
                "autoGenerated": True,
                "targetSegment": "CHURN_RISK",
                "targetUserIds": [c["id"] for c in churned_customers],
                "discountPercent": RECOVERY_DISCOUNT_PERCENT,
                "message": (
                    f"We miss you! Come back and enjoy {RECOVERY_DISCOUNT_PERCENT}% off your next order. "
                    f"Our {', '.join(top_item_names)} are waiting for you."
                ),
                "expiresInDays": 7,
                "generatedBy": "churn_prevention_agent",
                "generatedAt": datetime.now().isoformat(),
            }

            from ..tools.ops_http import post_json
            status, _ = await post_json(client, "/api/campaigns", campaign_payload)

            if status in (200, 201):
                campaigns_created += 1
                await _notify_managers(
                    client, store_id,
                    f"Churn Alert: {len(churned_customers)} high-value customers haven't ordered in "
                    f"{CHURN_WINDOW_DAYS}+ days. A win-back campaign draft is ready for your review.",
                )

    logger.info("Churn prevention complete: %d campaigns, %d customers", campaigns_created, customers_targeted)
    return {"campaigns_created": campaigns_created, "customers_targeted": customers_targeted}


async def _find_churned_customers(
    client: httpx.AsyncClient, store_id: str,
) -> List[Dict]:
    """Find customers who ordered >3 times in last 60 days but not in last 14 days."""
    from ..tools.ops_http import get_json, unwrap_list

    status, data = await get_json(
        client,
        "/api/customers",
        params={"storeId": store_id, "filter": "CHURN_RISK"},
    )
    if status == 200:
        return unwrap_list(data)

    # Fallback: get all customers and filter in Python
    all_status, all_body = await get_json(
        client,
        "/api/customers",
        params={"storeId": store_id},
    )
    if all_status != 200:
        return []

    all_customers = unwrap_list(all_body)
    churn_cutoff = datetime.now() - timedelta(days=CHURN_WINDOW_DAYS)

    churned = []
    for customer in all_customers:
        last_order = customer.get("lastOrderDate")
        total_orders = (customer.get("orderStats") or {}).get("totalOrders", 0)
        if last_order and total_orders >= QUALIFYING_ORDER_COUNT:
            last_order_dt = datetime.fromisoformat(last_order.replace("Z", "+00:00"))
            if last_order_dt < churn_cutoff:
                churned.append(customer)

    return churned


async def _get_top_items(
    client: httpx.AsyncClient, store_id: str,
) -> List[Dict]:
    from ..tools.ops_http import get_json

    status, data = await get_json(
        client,
        "/api/analytics",
        params={"storeId": store_id, "type": "top-products"},
    )
    if status == 200:
        if isinstance(data, list):
            return data[:3]
        items = data.get("topItems") or data.get("items") or []
        return items[:3]
    return []


async def _get_stores(client: httpx.AsyncClient) -> List[Dict]:
    from ..tools.ops_http import get_json, unwrap_list

    status, data = await get_json(client, "/api/stores")
    if status != 200:
        return []
    return unwrap_list(data)


async def _notify_managers(
    client: httpx.AsyncClient, store_id: str, message: str
):
    from ..tools.ops_http import get_json, post_json, unwrap_list

    status, managers = await get_json(
        client,
        "/api/users",
        params={"type": "MANAGER", "storeId": store_id},
    )
    if status != 200:
        return
    for manager in unwrap_list(managers):
        await post_json(
            client,
            "/api/notifications",
            {
                "userId": manager["id"],
                "type": "CHURN_ALERT",
                "title": "Customer Churn Alert",
                "message": message,
                "priority": "MEDIUM",
            },
        )
